repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-xml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: fix-encoding-pragma
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        args: [--config-file, mypy.ini]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        args: [--rcfile, .pylintrc]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest --config=pytest.ini
        language: system
        python: 3.10
